server.port=8302
spring.application.name=product-grpc-client

# Talk to gRPC server (plaintext for local demo)
grpc.client.productService.address=static://localhost:9090
grpc.client.productService.negotiationType=plaintext
