server.port=8400
spring.application.name=portal-bff

order-api.base-url=http://localhost:8401

# Keycloak as OIDC provider (SSO redirect)
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/interview

spring.security.oauth2.client.registration.keycloak.client-id=portal-bff
spring.security.oauth2.client.registration.keycloak.client-secret=portal-secret
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

management.endpoints.web.exposure.include=health,info
