server.port=8080
spring.application.name=api-gateway

# ---------- Routes ----------
# Client calls Gateway only. Gateway forwards to backends.

# /api/orders/**  →  order-backend:8101/orders/**
spring.cloud.gateway.routes[0].id=order-route
spring.cloud.gateway.routes[0].uri=http://localhost:8101
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/orders(?<segment>/?.*), /orders$\{segment}
spring.cloud.gateway.routes[0].filters[1]=AddRequestHeader=X-Gateway, api-gateway

# /api/products/**  →  product-backend:8102/products/**
spring.cloud.gateway.routes[1].id=product-route
spring.cloud.gateway.routes[1].uri=http://localhost:8102
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/products(?<segment>/?.*), /products$\{segment}
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Gateway, api-gateway

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
